repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: no-commit-to-branch
      args: [--branch, main]
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-ast
    - id: check-toml
    - id: debug-statements
    - id: detect-private-key
    - id: check-added-large-files
    - id: end-of-file-fixer
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.2
  hooks:
  - id: ruff
    types_or: [python, pyi, jupyter]
  - id: ruff-format
    types_or: [python, pyi, jupyter]
- repo: https://github.com/kynan/nbstripout
  rev: 0.6.1
  hooks:
    - id: nbstripout
# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v1.9.0
#   hooks:
#     - id: mypy
#       args: [--config-file=pyproject.toml]
#       exclude: tests/
- repo: https://github.com/python-poetry/poetry
  rev: 1.8.2
  hooks:
    - id: poetry-check
    - id: poetry-lock
      files: "pyproject.toml"
    - id: poetry-export
      args: ["-f", "requirements.txt", "--without-hashes", "--with", "dev", "-o", "requirements.txt"]
      files: "pyproject.toml"
